package com.email.writer.app;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.web.reactive.function.client.WebClient;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.ObjectMapper;

import java.util.Map;

@Service
public class EmailGeneratorService {

    private final WebClient webClient = WebClient.builder().build();

    @Value("${gemini.api.url}")
    private String geminiApiUrl;

    @Value("${gemini.api.key}")
    private String geminiApiKey;

    public String generateEmailReply(EmailRequest emailRequest) {

        String prompt = buildPrompt(emailRequest);

        // Request body for Gemini Interactions API
        Map<String, Object> requestBody = Map.of(
                "model", "gemini-3.7-flash",
                "input", prompt
        );

        try {
            String response = webClient.post()
                    .uri(geminiApiUrl)
                    .header("x-goog-api-key", geminiApiKey)
                    .header("Content-Type", "application/json")
                    .bodyValue(requestBody)
                    .retrieve()
                    .onStatus(
                            status -> status.isError(),
                            clientResponse -> clientResponse.bodyToMono(String.class)
                                    .map(body -> new RuntimeException(
                                            "Gemini returned " + clientResponse.statusCode()
                                                    + ": " + body
                                    ))
                    )
                    .bodyToMono(String.class)
                    .block();

            return extractResponseContent(response);

        } catch (Exception e) {
            e.printStackTrace();
            return "Gemini API Error: " + e.getMessage();
        }
    }

    private String extractResponseContent(String response) {

        try {
            ObjectMapper mapper = new ObjectMapper();
            JsonNode rootNode = mapper.readTree(response);

            JsonNode steps = rootNode.path("steps");

            if (!steps.isArray()) {
                return "Invalid response from Gemini: " + response;
            }

            for (JsonNode step : steps) {

                if ("model_output".equals(step.path("type").asText())) {

                    JsonNode content = step.path("content");

                    for (JsonNode contentBlock : content) {

                        if ("text".equals(contentBlock.path("type").asText())) {
                            return contentBlock.path("text").asText();
                        }
                    }
                }
            }

            return "No text response generated by Gemini.";

        } catch (Exception e) {
            return "Error processing Gemini response: " + e.getMessage();
        }
    }

    private String buildPrompt(EmailRequest emailRequest) {

        StringBuilder prompt = new StringBuilder();

        prompt.append(
                "Generate a professional email reply for the following email content. "
                        + "Do not generate a subject line. "
        );

        if (emailRequest.getTone() != null &&
                !emailRequest.getTone().isEmpty()) {

            prompt.append("Use a ")
                    .append(emailRequest.getTone())
                    .append(" tone. ");
        }

        prompt.append("\nOriginal email:\n")
                .append(emailRequest.getEmailContent());

        return prompt.toString();
    }
}